---
- name: Getting current nodes runnning on the cluster
  ansible.builtin.shell: kubectl get node | awk 'NR>1 {print $1}'
  delegate_to: "{{ groups['kubernetes_nodes'][0] }}"
  register: get_node_cmd
  changed_when: false

- name: Add current node to cluster
  block:
  - name: Get add-node command result from first node
    ansible.builtin.command: microk8s add-node
    delegate_to: "{{ groups['kubernetes_nodes'][0] }}"
    register: result
    changed_when: false

  - name: Join cluster with previous result command
    ansible.builtin.command: "{{ result.stdout_lines[1] }}"
    register: result
    changed_when: result.rc == 0

  - name: Update Kubernetes config file to default path
    ansible.builtin.command: microk8s config > $HOME/.kube/config
    changed_when: false

  - name: Wait for added node to be ready
    ansible.builtin.shell: kubectl get node {{ inventory_hostname }} | awk 'NR>1 {print $2}'
    register: current_node
    until:
    - current_node.stdout == 'Ready'
    retries: 30
    delay: 10
    changed_when: false

  when: "inventory_hostname not in get_node_cmd.stdout_lines"
