---
- name: Install epel-release
  ansible.builtin.yum:
    name: epel-release
    state: present
  register: epel_install
  retries: 5
  until: epel_install is success

- name: Install snapd
  ansible.builtin.yum:
    name: snapd
    state: present
  register: snapd_install
  retries: 5
  until: snapd_install is success

- name: Enable socket for snapd
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: snapd.socket

- name: Create symlink for snap command
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
