---
- name: Create default Kubernetes config directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: 0644
  register: result

- name: Fetch Kubernetes config file
  ansible.builtin.fetch:
    src: $HOME/.kube/config
    dest: ~/.kube/config
    flat: yes
  delegate_to: "{{ groups['kubernetes_nodes'][0] }}"
  register: result
